import 'package:flutter/material.dart';

const kUsername = 'username';
const kFullname = 'fullname';
const kEmail = 'email';
const kPassword = 'Password';
const kcreatedAt = 'createdAt';
const kUserCollication = 'users';
const kLostItemCollication = 'LostItem';
const kFoundItemCollication = 'FoundItem';
const kdescription = 'descreption';
const kphone = 'phone';
const kimage = 'image';
const klostdate = 'lostdate';
const klostname = 'name';
const kFoundname = 'name';
const kFoundDescreption = 'descreption';
const kFounddate = 'founddate';
const kFoundImage = 'image';
const kFoundPhone = 'phone';
